### ISSUE TITLE
Productionize speech-to-text pipeline

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/speech-to-text#7]
for the purpose of this ticket, the speech-to-text container covers the `speech_to_text.py` docker container, the AWS infrastructure it operates in for all 3 SDR envs (qa/stage/prod), and the SDR common-accessioning and workflow-server-rails pieces to get it to fit into our larger accessioning pipeline.

there are other higher level concerns/decisions that may block or otherwise affect deployment of the SDR speech-to-text service as a whole, covered in #1 and in our planning google doc.

@andrewjbtw's [Putting the Whisper pipeline into production](https://docs.google.com/document/d/1at7iE8Wnp2HcdB2eFk-VdtQf_lYBByx-dr3rNk9Mr8o/edit?tab=t.0#heading=h.tur7t93r0e6c) doc

- [x] https://github.com/sul-dlss/terraform-aws/issues/1170
- [x] https://github.com/sul-dlss/terraform-aws/issues/1177
- [x] https://github.com/sul-dlss/speech-to-text/issues/65
- [x] https://github.com/sul-dlss/speech-to-text/issues/46
- [x] https://github.com/sul-dlss/speech-to-text/issues/32
- [x] https://github.com/sul-dlss/speech-to-text/issues/61
- [x] https://github.com/sul-dlss/speech-to-text/issues/58
- [x] sul-dlss/common-accessioning#1363
  - [x] sul-dlss/common-accessioning#1350
  - [x] sul-dlss/common-accessioning#1356
  - [x] sul-dlss/common-accessioning#1358
  - [x] sul-dlss/common-accessioning#1359
  - [x] sul-dlss/common-accessioning#1360
  - [x] sul-dlss/common-accessioning#1361
  - [x] sul-dlss/common-accessioning#1362
  - [x] sul-dlss/common-accessioning#1462
- [x] sul-dlss/speech-to-text#92

**Comment by jmartin-sul** [comment]
@jmartin-sul retitle this ticket to be more specific

**Comment by jmartin-sul** [comment]
all subtasks done, and i can't think of any others to add.  afaik, this hasn't been enabled in production in the preassembly UI, but the various cloud resources have been provisioned and wired up the the common-accessioning pipeline.  and we think the code has been productionized, per this ticket.

closing.
